config:

  # countdown before teleporting, cancels on player move or damage
  countdown:
    enabled: true
    seconds: 5

  # how many seconds until a player can run the command again?
  region-cooldown:
    enabled: false
    seconds: 60

  global-cooldown:
    enabled: true
    seconds: 120

  global-economy:
    enabled: true

  # when creating a region, the border will display temporarily,
  # making it easier to find. Disabling it will make it not display
  # after a region is created or edited. only works on 1.13 - 1.17.
  display-border:
    enabled: true
    rgb: [0, 127, 255]
    seconds: 10
