config:

  # countdown before teleporting, cancels on player move or damage
  countdown:
    enabled: true
    seconds: 5

  # how many seconds until a player can run the command again?
  region-cooldown:
    enabled: false
    seconds: 60

  global-cooldown:
    enabled: true
    seconds: 120