name: CyberTravel
version: ${project.version}
main: net.zerotoil.cybertravel.CyberTravel
api-version: 1.16
authors: [ Kihsomray ]
description: Quickly teleport to checkpoints you've unlocked.
website: zerotoil.net
softdepend: [ Vault, PlaceholderAPI ]

commands:
  ctp:
    aliases:
      - fastteleport
      - ctcp
      - ftcp
      - ftp
      - fasttp
      - fteleport
      - fasttravel
      - fastravel
      - ftcheckpoint
      - cybertravel